### ISSUE TITLE
Unity plyaer crashes/Not responding on playing again.

### ISSUE THREAD

**Issue by musab1234** [LarrxX/OpenCV_Unity#1]
Plugin works as it described , but after playing scene again freezes unity player and unity editor becomes not responding. I have to restart unity to work again. Any idea to fix it ?

**Comment by LarrxX** [comment]
I think it might have something to do with not manually killing the OpenCV thread. I'll look into it when I get a chance

**Comment by musab1234** [comment]
OpenCV thread? you mean releasing camera/VideoCapture or something else?

**Comment by LarrxX** [comment]
I'm unable to reproduce your problem on my setup.

What versions of Unity and OpenCV are you using? And how is the plugin intergated in your project?

FYI, if you are rebuilding the DLL while Unity is running, Unity doesn't like that and the behavior you are getting is "normal".

**Comment by musab1234** [comment]
I am using unity 2019.2.13f1. I just compiled dll and generated swig wrappers files. Copied all into Plugin/Assets folder. When i hit play button it plays normally after i stop and play again its getting not respond. I am attaching screen shot. ( I am not rebuilding dll again & again i just did it one time only).

During first time run 
![image](https://user-images.githubusercontent.com/8913078/71346853-b58f3f80-258a-11ea-86e8-092d2815e7b4.png)

After running again it stuck like this
![image](https://user-images.githubusercontent.com/8913078/71346887-d788c200-258a-11ea-9cbc-19a5a4246ac5.png)

**Comment by musab1234** [comment]
Hi @LarrxX , can you tell , which unity version are you using please?
